# Generated by Django 2.2.6 on 2019-11-04 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('invitations', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escort',
            name='invitation_id',
        ),
        migrations.RemoveField(
            model_name='invitation',
            name='board_id',
        ),
        migrations.DeleteModel(
            name='Board',
        ),
        migrations.DeleteModel(
            name='Escort',
        ),
        migrations.DeleteModel(
            name='Invitation',
        ),
    ]
