# Generated by Django 2.2.6 on 2019-10-22 12:46

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.CharField(default='YAH0IzRO', max_length=8, unique=True)),
                ('created', models.DateTimeField(default=datetime.datetime(2019, 10, 22, 14, 46, 42, 861266))),
                ('confirmed', models.BooleanField(default=False)),
                ('isFamily', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Guest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Invitation')),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('guest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='guests.Guest')),
            ],
        ),
    ]
