# Generated by Django 2.2.6 on 2019-10-22 13:03

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('guests', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='invitation',
            name='created',
            field=models.DateTimeField(default=datetime.datetime(2019, 10, 22, 15, 3, 33, 878453)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='slug',
            field=models.CharField(default='m0r9NJlr', max_length=8, unique=True),
        ),
    ]
