# Generated by Django 2.2.6 on 2019-11-04 13:23

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Board',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('image', models.ImageField(default='default-boards.jpg', upload_to='static/img/boards/')),
                ('date_created', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 23, 21, 126458))),
                ('laste_modified', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 23, 21, 126458))),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 4, 14, 23, 21, 126458), null=True)),
                ('slug', models.CharField(default='qCSTv6vT', max_length=8, unique=True)),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('email', models.EmailField(default='', max_length=254)),
                ('phone', models.IntegerField(default='')),
                ('confirmed', models.BooleanField(default=False)),
                ('confirmation_date', models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 23, 21, 126458))),
                ('multiple_escort', models.BooleanField(default=False)),
                ('board', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Board')),
            ],
        ),
        migrations.CreateModel(
            name='Escort',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='', max_length=50)),
                ('surname', models.CharField(default='', max_length=50)),
                ('phone', models.IntegerField(default='')),
                ('email', models.EmailField(default='', max_length=254)),
                ('invitation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='boards.Invitation')),
            ],
        ),
    ]
