# Generated by Django 2.2.6 on 2019-11-04 13:42

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 42, 16, 708820)),
        ),
        migrations.AlterField(
            model_name='board',
            name='laste_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 42, 16, 708820)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='confirmation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 4, 14, 42, 16, 709821)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 4, 14, 42, 16, 709320), null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='slug',
            field=models.CharField(default='bc5duOox', max_length=8, unique=True),
        ),
    ]
