# Generated by Django 2.2.6 on 2019-11-05 06:14

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('boards', '0002_auto_20191104_1442'),
    ]

    operations = [
        migrations.AlterField(
            model_name='board',
            name='date_created',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 7, 14, 18, 483769)),
        ),
        migrations.AlterField(
            model_name='board',
            name='laste_modified',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 7, 14, 18, 483769)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='confirmation_date',
            field=models.DateTimeField(default=datetime.datetime(2019, 11, 5, 7, 14, 18, 484772)),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='created',
            field=models.DateTimeField(blank=True, default=datetime.datetime(2019, 11, 5, 7, 14, 18, 484772), null=True),
        ),
        migrations.AlterField(
            model_name='invitation',
            name='slug',
            field=models.CharField(default='SfecsWuc', max_length=8, unique=True),
        ),
    ]
